INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Shoshana', 'MABTzbsnWr%E1rUA', 'benanov@yahoo.ca', 'admin', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Alton', 'OSoDPD&ornGcHe2r', 'formis@comcast.net', 'admin', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Sue', 'VfpsY7nK+eM8uxMx', 'tarreau@mac.com', 'admin', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Tad', 'qhlKzHs6Tvz!Cb8#', 'wmszeliga@comcast.net', 'user', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Joann', 'FUPRJh6=oeqHHWQm', 'stevelim@outlook.com', 'user', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Moriah', 'y8RFNvNK^GKO0i3A', 'pkplex@comcast.net', 'user', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Soon', 'dqhCNP2U*jqX3t=Z', 'loscar@hotmail.com', 'user', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Aurelia', 'cOt5CRXVm!Sl&HcU', 'storerm@yahoo.com', 'user', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Shavonne', 'Y1CFkBRNxz6gQ=XR', 'mnemonic@msn.com', 'guest', 0, FALSE);
INSERT INTO USER (NAME, PASSWORD, EMAIL, ROLE, UPLOAD_COUNT, IS_BANNED) VALUES ('Roberto', 'iKF&Edyhy*zvd8Zk', 'kayvonf@optonline.net', 'guest', 0, FALSE);

INSERT INTO ROLE (ROLE_NAME, LEVEL) VALUES ('admin', 0);
INSERT INTO ROLE (ROLE_NAME, LEVEL) VALUES ('user', 1);
INSERT INTO ROLE (ROLE_NAME, LEVEL) VALUES ('guest', 2);